export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  groqTranscriptionModel: process.env.GROQ_TRANSCRIPTION_MODEL ?? "whisper-large-v3-turbo",
  groqChatModel: process.env.GROQ_CHAT_MODEL ?? "openai/gpt-oss-120b",
  sharePointSiteUrl: process.env.SHAREPOINT_SITE_URL ?? "https://abcstorage.sharepoint.com/transformaciondigital",
  sharePointListName: process.env.SHAREPOINT_LIST_NAME ?? "Reuniones Efectivas",
  sharePointColumnName: process.env.SHAREPOINT_COLUMN_NAME ?? "Nota",
};
